import { Filters } from '../types';
interface FilterPanelProps { filters: Filters; onFiltersChange: (filters: Filters) => void; onApply: () => void; onReset: () => void; }
export default function FilterPanel({ filters, onFiltersChange, onApply, onReset }: FilterPanelProps) {
  const update = (field: keyof Filters, value: string | string[]) => onFiltersChange({ ...filters, [field]: value });
  const toggle = (field: 'fuelTypes' | 'transmissions' | 'sources', value: string) => update(field, filters[field].includes(value) ? filters[field].filter(v => v !== value) : [...filters[field], value]);
  const checks = (field: 'fuelTypes' | 'transmissions' | 'sources', values: string[]) => <div className="space-y-2">{values.map(value => <label key={value} className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" checked={filters[field].includes(value)} onChange={() => toggle(field, value)} />{value}</label>)}</div>;
  const input = (label: string, field: 'maxPrice' | 'maxDistance' | 'maxMileage', placeholder: string) => <div><label className="block text-sm font-medium text-[#0f172a] mb-2">{label}</label><input type="number" value={filters[field]} onChange={e => update(field, e.target.value)} placeholder={placeholder} className="w-full px-3 py-2 border border-gray-300 rounded-lg outline-none" /></div>;
  return <div className="w-64 bg-white rounded-lg p-6 border border-gray-200 sticky top-20 max-h-[calc(100vh-6rem)] overflow-y-auto"><div className="flex justify-between items-center mb-6"><h3 className="text-lg font-semibold text-[#0f172a]">Filters</h3><button onClick={onReset} className="text-sm text-[#2563eb] hover:underline">Clear all</button></div><div className="space-y-6">{input('Max Budget', 'maxPrice', '£')}<div><label className="block text-sm font-medium text-[#0f172a] mb-2">Minimum Year</label><select value={filters.minYear} onChange={e => update('minYear', e.target.value)} className="w-full px-3 py-2 border rounded-lg"><option value="">Any</option>{[2024,2023,2022,2021,2020,2019,2018,2017,2016,2015].map(y => <option key={y}>{y}</option>)}</select></div><div><label className="block text-sm font-medium mb-2">Fuel Type</label>{checks('fuelTypes', ['Petrol','Diesel','Hybrid','Electric'])}</div><div><label className="block text-sm font-medium mb-2">Transmission</label>{checks('transmissions', ['Manual','Automatic'])}</div>{input('Max Distance (miles)', 'maxDistance', 'Miles')}<div><label className="block text-sm font-medium mb-2">Source</label>{checks('sources', ['eBay','Dealer Site','Local Garage','Partner Dealer'])}</div>{input('Max Mileage', 'maxMileage', 'Miles')}</div><div className="sticky bottom-0 pt-5 mt-6 bg-white border-t border-gray-100 space-y-2"><button onClick={onApply} className="w-full py-2.5 bg-[#2563eb] text-white rounded-lg font-medium">Update Results</button><button onClick={onReset} className="w-full py-2 text-[#2563eb] text-sm font-medium hover:underline">Reset Filters</button></div></div>;
}
